export const CHECK_TODO = "CHECK_TODO";
export const CHECK_TODO_ALL = "CHECK_TODO_ALL";
export const SHOW_ALL_TODO = "SHOW_ALL_TODO";
export const SHOW_ACTIVE_TODO = "SHOW_ACTIVE_TODO";
export const SHOW_COMPLETED_TODO = "SHOW_COMPLETED_TODO";
export const CLEAR_COMPLETED_TODO = "CLEAR_COMPLETED_TODO";
export const ADD_NEW_TODO = "ADD_NEW_TODO";
